### PR TITLE
Fix for issue #57

### PR DESCRIPTION
**Pull request by doychin**
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Isn't this going to just push the NPE somewhere else?

**Comment by Ladicek** [comment]
It shouldn't, as the `IllegalStateException` handler already returns `null`, so callers should expect that. Though I'd be curious to know when this happens, the issue doesn't go into detail.

**Comment by kenfinnigan** [comment]
Ok.

That's why I asked about the environment on the issue

**Comment by doychin** [comment]
I use Rest client in Arquilian @RunAsClient test that fails when I try to initialize my references to rest endpoints in @Before method.

**Comment by doychin** [comment]
I think the problem is that I have weld-se-core in my test class path.
I need it for other tests in the same project that are run using CdiRunner

**Comment by Ladicek** [comment]
That probably makes sense, but I'd personally ask @manovotn for review :-)

**Comment by manovotn** [comment]
@doychin Do you have a reproducer for this? Test or some repo where this can be debugged a bit.
Because it seems to be masking some other issue, `CDI` object is pretty defensive in how it handles [`CDI.current()`](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/inject/spi/CDI.java#L63-L91) call and should always give you either working provider, or an exception.

**Comment by doychin** [comment]
The problem is that I get this exception only on my CI machine. On my development machine I was unable to reproduce that problem. I will try to find a way to debug this.

**Comment by manovotn** [comment]
I would start by finding out what `CDIProvider` impl are you getting. I think there might be some from Arquillian or a Weld-provided one depending on your environment.

**Comment by doychin** [comment]
So the problem comes from the fact that there was a CDI container initialized before in the same JVM but at the moment when I try to build rest client there is none initialized. 

If you can create a some maven project that has 2 tests - one that runes with CdiRunner and another that just tries to create rest client you will see the failure. 

The problematic null value is returned from WeldSEProvider.getCDI method. It checks are there any containers there and if there is none it will return null.

**Comment by doychin** [comment]
CdiRunner test must run before rest client test.

**Comment by manovotn** [comment]
`CDI.current()` [checks for providers that return `null`](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/inject/spi/CDI.java#L87) (on `getCDI()` call) and doesn't treat them as valid.
Therefore `WeldSEProvider.getCDI()` (correctly) returning null shouldn't be a problem.

**Comment by doychin** [comment]
Try to run this code:

import javax.enterprise.inject.se.SeContainer;
import javax.enterprise.inject.se.SeContainerInitializer;
import javax.enterprise.inject.spi.CDI;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;
import java.net.MalformedURLException;
import java.net.URL;

import org.eclipse.microprofile.rest.client.RestClientBuilder;

public class NPEWithCDIAndRestClient {

    public static void main(String[] args) {
        SeContainer container = SeContainerInitializer.newInstance()
                                                      .disableDiscovery()
                                                      .addBeanClasses(BeanClass.class)
                                                      .initialize();
        CDI.current().getBeanManager();
        container.close();

        try {
            RestClientBuilder.newBuilder()
                             .baseUrl(new URL("http://localhost"))
                             .build(TestRestInterface.class);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }

    public static class BeanClass {

    }

    @Path("/")
    public interface TestRestInterface {

        @GET
        Response get();
    }
}

**Comment by doychin** [comment]
The critical call is CDI.current().getBeanManager();
It caches the cdiProvider and reuses it even when there is no currently active container.

**Comment by manovotn** [comment]
Ah, right, I can see the problem now. Thanks for explanation.

**Comment by doychin** [comment]
Do you think is a good idea to introduce also change to CDI.getCDIProvider() in case configuredProvider is not null to also check for configuredProvider.getCDI() != null?

**Comment by doychin** [comment]
Actually the bug is in WeldSeProvider.getCDI().
It should not return null in the first place.

**Comment by manovotn** [comment]
Depends, if it threw ISE right away  then in a situation when you have no running container and access `CDI.current()` for the first time, Weld provider will throw ISE even through there might be different providers on the classpath that would work. CDI code doesn't account for providers blowing up with ISE.

**Comment by kenfinnigan** [comment]
On looking at the surrounding code and the context, I think this change is good.

It should be possible to use REST Client with just the builder API if CDI is not present at all

**Comment by manovotn** [comment]
The change is definitely good, we strayed away from the original PR here.
We'll continue that discussion on respective issues :)

**Pull request merged**
